Repository memetionary/memetionary-fe, pull requests merged in 2024-05, with the labels that each got.

#6 Tailwind 테마 설정 추가 및 yarn 도입
  memetionary/.storybook/preview.ts
  memetionary/package-lock.json
  memetionary/src/app/globals.css
  memetionary/src/app/layout.tsx
  memetionary/src/styles/globals.css
  memetionary/tailwind.config.ts
  memetionary/yarn.lock
Labels: feature, env

#9 Feat/meme page
  memetionary/next.config.mjs
  memetionary/src/app/meme/[id]/layout.tsx
  memetionary/src/app/meme/[id]/page.tsx
  memetionary/src/assets/icons/IconEnvelope.tsx
  memetionary/src/assets/icons/IconEyeSolid.tsx
  memetionary/src/assets/icons/IconKakaoSharing.tsx
  memetionary/src/assets/icons/IconKakaotalk.tsx
  memetionary/src/assets/icons/IconPaperclip.tsx
  memetionary/src/assets/icons/IconShareNodes.tsx
  memetionary/src/assets/icons/IconThumbsDown.tsx
  memetionary/src/assets/icons/IconThumbsDownSolid.tsx
  memetionary/src/assets/icons/IconThumbsUp.tsx
  memetionary/src/assets/icons/IconThumbsUpSolid.tsx
  memetionary/src/assets/icons/IconUserRegular.tsx
  memetionary/src/assets/icons/IconUserSolid.tsx
  memetionary/src/assets/icons/index.ts
  memetionary/src/assets/svgs/icon-envelope.svg
  memetionary/src/assets/svgs/icon-eye-solid.svg
  memetionary/src/assets/svgs/icon-kakaotalk.svg
  memetionary/src/assets/svgs/icon-paperclip.svg
  memetionary/src/assets/svgs/icon-share-nodes.svg
  memetionary/src/assets/svgs/icon-thumbs-down-solid.svg
  memetionary/src/assets/svgs/icon-thumbs-down.svg
  memetionary/src/assets/svgs/icon-thumbs-up-solid.svg
  memetionary/src/assets/svgs/icon-thumbs-up.svg
  memetionary/src/assets/svgs/icon-user-regular.svg
  memetionary/src/assets/svgs/icon-user-solid.svg
  memetionary/src/components/Meme/Article/index.tsx
  memetionary/src/components/Meme/DetailAction/index.tsx
  memetionary/src/components/Meme/Evaluation/index.tsx
  memetionary/src/components/Meme/Example/Bubble.tsx
  memetionary/src/components/Meme/Example/index.tsx
  memetionary/src/components/Meme/FooterDetail/index.tsx
  memetionary/src/components/Meme/TagList/Tag.tsx
  memetionary/src/components/Meme/TagList/index.tsx
  memetionary/src/components/Meme/TitleDetail/index.tsx
  memetionary/src/components/Meme/dummy.ts
  memetionary/src/components/ShareButton/index.tsx
  memetionary/src/components/Video/index.tsx
  memetionary/src/utils/timeUtils.ts
Labels: feature

#7 메인 페이지, 검색 페이지 마크업
  memetionary/.prettierrc
  memetionary/.storybook/main.ts
  memetionary/package.json
  memetionary/src/app/contact/page.tsx
  memetionary/src/app/layout.tsx
  memetionary/src/app/meme/[id]/layout.tsx
  memetionary/src/app/meme/[id]/page.tsx
  memetionary/src/app/page.tsx
  memetionary/src/assets/icons/IconBad.tsx
  memetionary/src/assets/icons/IconGood.tsx
  memetionary/src/assets/icons/IconLogo.tsx
  memetionary/src/assets/icons/IconMeme.tsx
  memetionary/src/assets/icons/IconMemeColor.tsx
  memetionary/src/assets/icons/IconOpinion.tsx
  memetionary/src/assets/icons/IconRandom.tsx
  memetionary/src/assets/icons/IconSearch.tsx
  memetionary/src/assets/icons/index.ts
  memetionary/src/assets/svgs/icon-bad.svg
  memetionary/src/assets/svgs/icon-good.svg
  memetionary/src/assets/svgs/icon-logo.svg
  memetionary/src/assets/svgs/icon-meme-color.svg
  memetionary/src/assets/svgs/icon-meme.svg
  memetionary/src/assets/svgs/icon-opinion.svg
  memetionary/src/assets/svgs/icon-random.svg
  memetionary/src/assets/svgs/icon-search.svg
  memetionary/src/components/Button/index.tsx
  memetionary/src/components/Input/index.tsx
  memetionary/src/components/Layout/Header/index.tsx
  memetionary/src/components/Layout/Main/index.tsx
  memetionary/src/components/Layout/index.tsx
  memetionary/src/components/Meme/DetailAction/index.tsx
  memetionary/src/components/Meme/Evaluation/index.tsx
  memetionary/src/components/Meme/Example/Bubble.tsx
  memetionary/src/components/Meme/Example/index.tsx
  memetionary/src/components/Meme/TagList/Tag.tsx
  memetionary/src/components/ShareButton/index.tsx
  memetionary/tailwind.config.ts
  memetionary/yarn.lock
Labels: style, feature

#14 밈 검색 기능 구현
  memetionary/src/app/api/meme/data.ts
  memetionary/src/app/api/meme/list/route.ts
  memetionary/src/app/api/meme/trend/route.ts
  memetionary/src/app/page.tsx
  memetionary/src/app/search/[keyword]/page.tsx
  memetionary/src/app/search/layout.tsx
  memetionary/src/app/search/page.tsx
  memetionary/src/assets/icons/IconBad.tsx
  memetionary/src/assets/icons/IconGood.tsx
  memetionary/src/assets/icons/IconLeftDirection.tsx
  memetionary/src/assets/icons/IconLogo.tsx
  memetionary/src/assets/icons/IconMeme.tsx
  memetionary/src/assets/icons/IconMemeColor.tsx
  memetionary/src/assets/icons/IconOpinion.tsx
  memetionary/src/assets/icons/IconRandom.tsx
  memetionary/src/assets/icons/IconRightDirection.tsx
  memetionary/src/assets/icons/IconSearch.tsx
  memetionary/src/assets/icons/index.ts
  memetionary/src/assets/svgs/icon-left-direction.svg
  memetionary/src/assets/svgs/icon-right-direction.svg
  memetionary/src/components/Meme/Article/index.tsx
  memetionary/src/components/Meme/Evaluation/index.tsx
  memetionary/src/components/Meme/MemeList/index.tsx
  memetionary/src/components/Meme/TitleDetail/index.tsx
  memetionary/src/components/Meme/TrendMeme/index.tsx
  memetionary/src/components/Pagination/PaginationItem.tsx
  memetionary/src/components/Pagination/index.tsx
Labels: feature

#15 밈 상세 조회 API 및 메일링 기능 구현
  memetionary/package-lock.json
  memetionary/package.json
  memetionary/src/api/contact/index.ts
  memetionary/src/api/meme/index.ts
  memetionary/src/app/api/contact/route.ts
  memetionary/src/app/api/meme/[id]/route.ts
  memetionary/src/app/api/meme/data.ts
  memetionary/src/app/contact/layout.tsx
  memetionary/src/app/contact/page.tsx
  memetionary/src/app/meme/[id]/page.tsx
  memetionary/src/components/Input/index.tsx
  memetionary/src/components/Meme/Example/Bubble.tsx
  memetionary/src/components/Meme/Example/index.tsx
  memetionary/src/components/Meme/FooterDetail/index.tsx
  memetionary/src/components/Meme/MemeList/index.tsx
  memetionary/src/components/Meme/Thumbnail/index.tsx
  memetionary/src/components/Meme/TitleDetail/index.tsx
  memetionary/src/components/Meme/dummy.ts
  memetionary/src/components/Select/index.tsx
  memetionary/src/components/ShareButton/index.tsx
  memetionary/src/components/TextArea/index.tsx
  memetionary/src/components/Video/index.tsx
  memetionary/src/utils/timeUtils.ts
  memetionary/src/utils/validator/contactForm.ts
  memetionary/src/utils/validator/index.ts
Labels: feature

#17 랜덤 밈 검색하기
  memetionary/src/api/meme/index.ts
  memetionary/src/app/api/meme/random/route.ts
  memetionary/src/app/contact/layout.tsx
  memetionary/src/app/contact/page.tsx
  memetionary/src/app/meme/[id]/page.tsx
  memetionary/src/app/page.tsx
  memetionary/src/components/Layout/Header/index.tsx
  memetionary/src/components/Layout/Main/index.tsx
  memetionary/src/components/Meme/DetailAction/index.tsx
  memetionary/src/components/Meme/Example/Bubble.tsx
  memetionary/src/components/Meme/Example/index.tsx
  memetionary/src/components/Meme/FooterDetail/index.tsx
  memetionary/src/components/Meme/TagList/Tag.tsx
  memetionary/src/components/Meme/TagList/index.tsx
  memetionary/src/components/Meme/Thumbnail/index.tsx
  memetionary/src/components/RandomButton/index.tsx
  memetionary/src/components/Select/index.tsx
  memetionary/src/components/TextArea/index.tsx
  memetionary/src/components/Video/index.tsx
  memetionary/src/hooks/useForm.ts
  memetionary/src/utils/randomUtil.ts
  memetionary/src/utils/validator/contactForm.ts
  memetionary/src/utils/validator/index.ts
Labels: feature
